apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE

---

apiVersion: v1
kind: Service
metadata:
  name: $DEPLOYMENT_NAME-service
  namespace: $NAMESPACE
spec:
  selector:
    app: $DEPLOYMENT_NAME
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $NAMESPACE
  name: $DEPLOYMENT_NAME-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        app: $DEPLOYMENT_NAME
    spec:
      containers:
        - name: $DEPLOYMENT_NAME
          image: nginxinc/nginx-unprivileged:stable-alpine
          ports:
            - name: http
              containerPort: 8080
