apiVersion: v1
kind: Pod
metadata:
  name: time_skew
  labels:
    scenario: time_skew
spec:
  hostNetwork: true
  containers:
  - name: fedtools
    image: docker.io/fedora/tools
    command:
    - /bin/sh
    - -c
    - |
      sleep infinity