name: Kraken Functional Tests
on: issue_comment
  types:
    - created

jobs:
  crc-create:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        echo "it works!"

    

    



