name: Kraken Functional Tests
on: issue_comment

jobs:
  crc-create:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/ocp-test')
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        echo "it works!"

    

    



